name: Validate Solution
 
on:
  push:
  pull_request:

env:
  PORT: 4000
  MONGO_URL: mongodb://localhost:27017/db_auth_api
  SECREDT_KEY_AUTH: B398_cv_pp!12df
  EXPIRESIN: 60s
  SECREDT_KEY_REFRESH: Hj+=Y:Zut87Yy09w1
  EXPIRESIN_REFRESH: 5d
  JWT_IGNORE_EXPIRATION: false
  PORT_MCRO: 4010
  HOST_MCRO: localhost

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-port: 27017
        mongodb-db: db_auth_api
        #mongodb-username: usuario
        #mongodb-password: senha  

    - name: Install dependencies
      run: yarn install --frozen-lockfile      
      
    - name: List output files
      run: find build/ -print

    - name: Running e2e testing
      run: yarn test:e2e

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        #git-ftp-args: '--all'
        #server-dir: ${{ secrets.FTP_APP_DIR }}