name: Validate Data
 
on:
  push:
  pull_request:

jobs:
  validate-data:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      
      - run: yarn
<<<<<<< HEAD
      - run: yarn test:unit 
=======
      - run: yarn test:unit
>>>>>>> 162117e02f150a8fa524080ef52ed546f5a35c78
